version: '3'

services:
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  monkey-island:
    container_name: monkey-island
    hostname: monkey-island
    image: infectionmonkey/monkey-island:e7c59c79d
    environment:
      - MONKEY_MONGO_URL=mongodb://mongo:27017/monkey_island_test
    ports:
      - 5000:5000
    depends_on:
      - mongo
  hello:
    container_name: hello
    hostname: hello
    image: infectionmonkey/ssh1
    command: '/usr/sbin/sshd -D && sh -c "trap : TERM INT; tail -f /dev/null & wait"'
volumes:
  db:
